# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fafb1b2996f1c5e5ef3427b4b00d0d58b105649fde0815c0fe12b5a6cac95ab2a12bcac94717df7d6c706c90e32152c6cc9707502c5d3209aa599c493cb25943

test:
  secret_key_base: b19b235e8c701fbdb24b4d6c3db658140a35de5c64d24bc8479a448e9a65831eaebd7928530b658e4fe4550a77e71fb8f9ca0af8843713354031f0a5f2ed8561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
